2020-11-07 18:17:11,506 INFO: Microblog startup [in /home/liza/PycharmProjects/microblog2/app/__init__.py:45]
2020-11-08 13:01:53,240 INFO: Microblog startup [in /home/liza/PycharmProjects/microblog2/app/__init__.py:45]
2020-11-08 13:02:06,733 INFO: Microblog startup [in /home/liza/PycharmProjects/microblog2/app/__init__.py:45]
2020-11-08 13:02:22,354 INFO: Microblog startup [in /home/liza/PycharmProjects/microblog2/app/__init__.py:45]
2020-11-08 14:13:31,244 INFO: Microblog startup [in /home/liza/PycharmProjects/microblog2/app/__init__.py:45]
2020-11-08 14:13:36,676 INFO: Microblog startup [in /home/liza/PycharmProjects/microblog2/app/__init__.py:45]
2020-11-08 14:20:48,927 INFO: Microblog startup [in /home/liza/PycharmProjects/microblog2/app/__init__.py:45]
2020-11-08 14:22:13,695 INFO: Microblog startup [in /home/liza/PycharmProjects/microblog2/app/__init__.py:45]
2020-11-08 14:23:30,125 INFO: Microblog startup [in /home/liza/PycharmProjects/microblog2/app/__init__.py:45]
2020-11-08 14:23:50,077 INFO: Microblog startup [in /home/liza/PycharmProjects/microblog2/app/__init__.py:45]
2020-11-08 14:25:13,201 INFO: Microblog startup [in /home/liza/PycharmProjects/microblog2/app/__init__.py:45]
2020-11-08 14:26:12,482 INFO: Microblog startup [in /home/liza/PycharmProjects/microblog2/app/__init__.py:45]
2020-11-08 14:26:23,926 INFO: Microblog startup [in /home/liza/PycharmProjects/microblog2/app/__init__.py:45]
2020-11-08 14:27:16,467 INFO: Microblog startup [in /home/liza/PycharmProjects/microblog2/app/__init__.py:45]
2020-11-08 14:27:43,015 INFO: Microblog startup [in /home/liza/PycharmProjects/microblog2/app/__init__.py:45]
2020-11-08 16:59:34,566 INFO: Microblog startup [in /home/liza/PycharmProjects/microblog2/app/__init__.py:45]
2020-11-08 20:25:13,159 INFO: Microblog startup [in /home/liza/PycharmProjects/microblog2/app/__init__.py:45]
2020-11-08 20:25:19,200 ERROR: Exception on /index [GET] [in /home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/liza/PycharmProjects/microblog2/app/routes.py", line 23, in index
    return render_template('index.html', title='Home', posts=posts)
NameError: name 'posts' is not defined
2020-11-08 20:30:56,691 INFO: Microblog startup [in /home/liza/PycharmProjects/microblog2/app/__init__.py:45]
2020-11-08 20:30:59,707 ERROR: Exception on /index [GET] [in /home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/liza/PycharmProjects/microblog2/app/routes.py", line 32, in index
    return render_template('index.html', title='Home', posts=posts)
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/liza/PycharmProjects/microblog2/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/liza/PycharmProjects/microblog2/app/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "/home/liza/PycharmProjects/microblog2/app/templates/index.html", line 6, in block "content"
    {{ form.hidden_tag() }}
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2020-11-08 20:31:15,398 ERROR: Exception on /index [GET] [in /home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/liza/PycharmProjects/microblog2/app/routes.py", line 32, in index
    return render_template('index.html', title='Home', posts=posts, form=form)
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/liza/PycharmProjects/microblog2/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/liza/PycharmProjects/microblog2/app/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "/home/liza/PycharmProjects/microblog2/app/templates/index.html", line 6, in block "content"
    {{ form.hidden_tag() }}
  File "/home/liza/PycharmProjects/microblog2/venv/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2020-11-08 21:47:57,948 INFO: Microblog startup [in /home/liza/PycharmProjects/microblog2/app/__init__.py:46]
2020-11-08 21:48:36,370 INFO: Microblog startup [in /home/liza/PycharmProjects/microblog2/app/__init__.py:46]
2020-11-09 23:24:19,550 INFO: Microblog startup [in /home/liza/PycharmProjects/microblog2/app/__init__.py:46]
